/* autoconfig generated by building system */ 
#define NAND_SUPPORT y 
#define SDMMC_SUPPORT y 
#define EMMC_SUPPORT y 
#define DISABLE_NFI_DMA 1 
#define DUMP_SPEED 1 
#define ENABLE_LOG_FOR_INIT_STAGE 1 
#define DA_MODE_FPGA 3 
#define DA_MODE_BRINGUP 2 
#define DA_MODE_NORMAL 1 
#define DA_MODE DA_MODE_NORMAL 
#define DA_ENABLE_SECURITY 1 
#define BB_MT8167 1 
#ifdef STAGE_DA_INIT 
#endif 
#ifdef STAGE_DA_INIT 
#endif 
#ifdef STAGE_DA_INIT 
#endif 
#ifdef STAGE_DA_LOOP 
#define ENABLE_EMMC_DMA 1 
#endif 
#ifdef STAGE_DA_LOOP 
#define ENABLE_USB_DMA 1 
#endif 
#ifdef STAGE_DA_LOOP 
#endif 
#define  DA_INIT_BASE_ADDRESS 0x200000 
#define  DA_INIT_SIZE 0x40000 
#define  DA_INIT_HEAP_BASE_ADDRESS 0x100000 
#define  DA_INIT_HEAP_BASE_SIZE 0x10000 
#define  DA_DRAM_BASE_ADDRESS 0x40000000 
#define  DA_DRAM_SIZE 0x10000000 
#define  ARM_WITH_CP15 1  
#define  ARM_WITH_MMU 1  
#define  ARM_ISA_ARMV7 1  
#define  ARM_WITH_VFP 1  
#define  ARM_WITH_NEON 1  
#define  ARM_WITH_THUMB 1  
#define  ARM_WITH_THUMB2 1  
#define  ARM_WITH_CACHE 1 
#define  ARM_WITH_L2 1 
#define  ENABLE_L2_SHARING 1 
#define  ARM_CPU_CORTEX_A53 1 
