/* autoconfig generated by building system */ 
#define FEATURE_NAND_SUPPORT "y" 
#define FEATURE_SDMMC_SUPPORT "y" 
#define FEATURE_EMMC_SUPPORT "y" 
#define FEATURE_COMBO_MCP "y" 
#define FEATURE_SW_SEC_BOOT "y" 
