OUTPUT_ARCH(arm)
MEMORY {
	text (rwx) : ORIGIN = 0x200000 ,LENGTH = 1M
	bss	(rwx) : ORIGIN = 0x200000 + LENGTH(.all)+LENGTH(.section_end),LENGTH = 1M
}
SECTIONS
{
	. = 0x200000;
	__text_start = .;
    .all ALIGN(8) : {*(.text .data .rodata)} > text 
	.section_end ALIGN(8) : {*(.section_end)}
	. = .;
	__bss_start = .;
	.bss ALIGN(8) : {*(.bss)} 			> bss
	.bss_static ALIGN(8) : {.bss.*}		
	. = .;
	__bss_end = .;
}


