#ifndef STORAGE_CTRL_INTERFACE_H
#define STORAGE_CTRL_INTERFACE_H

#include "sys/types.h"

typedef enum {
   STORAGE_CRCODE_GET_ACTIVE_BOOT_SECTION = 1,
   STORAGE_CRCODE_OTP_LOCK = 2,
   STORAGE_CRCODE_RECTIFY_OTP_ADDRESS =3,
   STORAGE_CRCODE_DOWNLOAD_BL_PROCESS =4, 
   STORAGE_CRCODE_CHECK_OTP_LOCK_STATUS =5, 
   STORAGE_CRCODE_DISABLE_EMMC_RESET_PIN=6, 
   STORAGE_CRCODE_SET_EMMC_RESET_PIN=7, 
   STORAGE_CRCODE_CHECK_RPMB_KEY_STATUS=8,   //check if rpmb key has been written, if written, dl will be forbidden
}STORAGE_CRTL_CODE_E;



#endif

