O_TARGET	:= nand_lib.o

obj-y 		:= nand_drv_COMMON_v5.o
obj-y 		+= nand_dev_tbl.o
obj-y 		+= nand_drv_HYNIX.o
obj-y 		+= nand_drv_KINGSTON.o
obj-y 		+= nand_drv_SAMSUNG.o
obj-y 		+= nand_drv_TOSHIBA.o

include $(TOPDIR)/Rules.make
