/*****************************************************************************
*  Copyright Statement:
*  --------------------
*  This software is protected by Copyright and the information contained
*  herein is confidential. The software may not be copied and the information
*  contained herein may not be used or disclosed except with the written
*  permission of MediaTek Inc. (C) 2009
*
*  BY OPENING THIS FILE, BUYER HEREBY UNEQUIVOCALLY ACKNOWLEDGES AND AGREES
*  THAT THE SOFTWARE/FIRMWARE AND ITS DOCUMENTATIONS ("MEDIATEK SOFTWARE")
*  RECEIVED FROM MEDIATEK AND/OR ITS REPRESENTATIVES ARE PROVIDED TO BUYER ON
*  AN "AS-IS" BASIS ONLY. MEDIATEK EXPRESSLY DISCLAIMS ANY AND ALL WARRANTIES,
*  EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE IMPLIED WARRANTIES OF
*  MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE OR NONINFRINGEMENT.
*  NEITHER DOES MEDIATEK PROVIDE ANY WARRANTY WHATSOEVER WITH RESPECT TO THE
*  SOFTWARE OF ANY THIRD PARTY WHICH MAY BE USED BY, INCORPORATED IN, OR
*  SUPPLIED WITH THE MEDIATEK SOFTWARE, AND BUYER AGREES TO LOOK ONLY TO SUCH
*  THIRD PARTY FOR ANY WARRANTY CLAIM RELATING THERETO. MEDIATEK SHALL ALSO
*  NOT BE RESPONSIBLE FOR ANY MEDIATEK SOFTWARE RELEASES MADE TO BUYER'S
*  SPECIFICATION OR TO CONFORM TO A PARTICULAR STANDARD OR OPEN FORUM.
*
*  BUYER'S SOLE AND EXCLUSIVE REMEDY AND MEDIATEK'S ENTIRE AND CUMULATIVE
*  LIABILITY WITH RESPECT TO THE MEDIATEK SOFTWARE RELEASED HEREUNDER WILL BE,
*  AT MEDIATEK'S OPTION, TO REVISE OR REPLACE THE MEDIATEK SOFTWARE AT ISSUE,
*  OR REFUND ANY SOFTWARE LICENSE FEES OR SERVICE CHARGE PAID BY BUYER TO
*  MEDIATEK FOR SUCH MEDIATEK SOFTWARE AT ISSUE.
*
*  THE TRANSACTION CONTEMPLATED HEREUNDER SHALL BE CONSTRUED IN ACCORDANCE
*  WITH THE LAWS OF THE STATE OF CALIFORNIA, USA, EXCLUDING ITS CONFLICT OF
*  LAWS PRINCIPLES.  ANY DISPUTES, CONTROVERSIES OR CLAIMS ARISING THEREOF AND
*  RELATED THERETO SHALL BE SETTLED BY ARBITRATION IN SAN FRANCISCO, CA, UNDER
*  THE RULES OF THE INTERNATIONAL CHAMBER OF COMMERCE (ICC).
*
*****************************************************************************/

/*****************************************************************************
 *
 * Filename:
 * ---------
 *   GFH_status.h
 *
 * Project:
 * --------
 *   BOOTROM
 *
 * Description:
 * ------------
 *   GFH(General File Header) header definition (eg: FILE_INFO)
 *
 * Author:
 * -------
 *   Clean Room
 *
 ****************************************************************************/
#ifndef __GFH_STATUS_H__
#define __GFH_STATUS_H__

#include "SW_TYPES.H"

typedef enum {
// OK
     B_OK = 0

// Error
	,E_ERROR = (U32)0x1000
    ,E_GFH_INVALID_PARAM
    ,E_GFH_HANDLE_NOT_INIT
    ,E_GFH_NOT_FOUND
    ,E_GFH_INVALID_TYPE
	,E_GFH_INVALID_SIZE
	// FILE_INFO
    ,E_GFH_FILE_INFO_NOT_FOUND
    ,E_GFH_FILE_INFO_INVALID_CONTENT_OFFSET
    ,E_GFH_FILE_INFO_INVALID_FILE_LEN
	,E_GFH_FILE_INFO_INVALID_SIG_LEN
	,E_GFH_FILE_INFO_FILE_LEN_EXCEED_MAX_SIZE
	,E_GFH_FILE_INFO_INVALID_JUMP_OFFSET 
	// SCTRL_CERT
	,E_GFH_SCTRL_CERT_NOT_FOUND
	,E_GFH_SCTRL_CERT_INVALID_MAGIC
	,E_GFH_SCTRL_CERT_INVALID_SIG_TYPE
	// TOOL_AUTH
	,E_GFH_TOOL_AUTH_NOT_FOUND
	,E_GFH_TOOL_AUTH_INVALID_DA_HASH_NUM
	,E_GFH_TOOL_AUTH_INVALID_BROM_VERIFIED_NUM
	,E_GFH_TOOL_AUTH_INVALID_SIG_TYPE
	// AC Clone
	,E_GFH_ANTI_CLONE_NOT_FOUND
	,E_AC_OFFSET_OR_LEN_INVALID
	,E_AC_FILE_CONTENT_LEN_INVALID

    ,E_END	= (U32)0xFFFFFFFF
} GFH_STATUS;

#endif
